[package]
name = "globaltrace"
version = "0.1.0"
authors = ["Felipe <fdns@niclabs.cl>"]

[dependencies]

[dependencies.pnet]
git = "https://github.com/fdns/libpnet/"
rev = "c9a9a385f18c11c1a059e1c744f158523086349d"