[package]
name = "ping"
version = "0.1.0"
authors = ["Felipe <fdns@niclabs.cl>"]

[dependencies]
ratelimit_meter = "2.0.0"
log = "0.4.4"

[dependencies.pnet]
git = "https://github.com/libpnet/libpnet/"
rev = "743e59994b5e3b9d666cc7f7500e37ee7bbde6f7"
